import kafka

consumer = kafka.KafkaConsumer(group_id='test',
                               api_version=(2, 10, 0), bootstrap_servers=['server'])
consumer.topics()

a = {"log_type": "finder", "status": 1000, "date": "2022-06-07 15:34:57", "uid": "7733809311", "ip": "117.61.101.130",
     "Mozilla": "10C5395060", "module": [{"cate": "1006",
                                          "info": [{"containerid": "102803_ctg1_1780_-_ctg1_1780", "name": "发现"},
                                                   {"containerid": "232673", "name": "视频"},
                                                   {"containerid": "232660", "name": "娱乐"},
                                                   {"containerid": "231230_-_discover_-_index", "name": "体育"},
                                                   {"containerid": "232300_cardlist_discover_games", "name": "游戏"}]},
                                         {"cate": "1000",
                                          "info": [{"key": "全国甲卷 难"}, {"search_flag": "0", "key": "#山东考生押中高考作文题#"},
                                                   {"adid": 156717, "key": "#宝藏零食种草机#"},
                                                   {"search_flag": "5", "key": "#向往的生活导演否认有洗碗阿姨#"},
                                                   {"search_flag": "0", "key": "#高考语文默写#"},
                                                   {"search_flag": "0", "key": "#KPL夏季赛火热开打#"},
                                                   {"search_flag": "5", "key": "#华晨宇挡开路人手机#"},
                                                   {"search_flag": "0", "key": "#iOS16支持Switch手柄#"},
                                                   {"search_flag": "0", "key": "#美国丢弃了超8210万剂新冠疫苗#"},
                                                   {"search_flag": "0", "key": "红楼梦"},
                                                   {"search_flag": "3", "key": "陈晓婚礼 柯南主题曲"}, {"nav": "more"}]},
                                         {"cate": "1005", "info": [
                                             [{"pos": 0, "adid": "156832", "show_type": 2, "media_type": "image"}],
                                             [{"pos": 0, "adid": "156550", "show_type": 2, "media_type": "image"}],
                                             [{"pos": 0, "adid": "156549", "show_type": 2, "media_type": "image"}],
                                             [{"pos": 0, "adid": "156534", "show_type": 2, "media_type": "image"}],
                                             [{"pos": 0, "adid": "156841", "show_type": 2, "media_type": "image"}], [
                                                 {"pos": 0, "adid": "156751", "key": "领航计划", "is_topic": "1",
                                                  "show_type": 2, "media_type": "image"}]]}, {"cate": "1001", "info": [
            {"id": 329, "code": "kyqz"}, {"id": 319, "code": "hotsquare"}, {"id": 324, "code": "HotTopic"},
            {"id": 11, "code": "caijing"}, {"id": 12, "code": "yinyue"}, {"id": 3, "code": "youxi"},
            {"id": 313, "code": "bendi"}, {"id": 120, "code": "saishi"}, {"id": 16, "code": "meishi"},
            {"id": 310, "code": "chaoliu"}, {"id": 176, "code": "chaohua"}, {"id": 320, "code": "Ranking"},
            {"id": 1, "code": "zhaoren"}, {"id": 4, "code": "zhibo"}, {"id": 15, "code": "qiche"},
            {"id": 215, "code": "shiyong"}, {"id": 325, "code": "discussroom"}, {"id": 170, "code": "edu"},
            {"id": 14, "code": "fangchan"}, {"id": 10, "code": "hongrentao"}, {"id": 5, "code": "dianying"},
            {"id": 308, "code": "xinzhi"}, {"id": 169, "code": "weigongyi"}, {"id": 207, "code": "huodong"},
            {"id": 235, "code": "muying"}, {"id": 262, "code": "yushi"}]}], "v_p": "90",
     "cid": "102803_ctg1_1780_-_ctg1_1780", "sid": "t_wap_android", "type": "ctg1", "page": 1, "seqid": 2129113823,
     "nettype": "wifi", "gis": ",", "ua": "HUAWEI-VOG-AL00__weibo__12.5.3__android__android10", "refer": "",
     "uicode": "10001344", "luicode": "", "lfid": "",
     "ext": [{"misdtm": 1654587297559}, {"wm": "9006_2001"}, {"city_code": "800863306"}, {"web_degrade": "0"},
             {"ab": "5238-g1,7865-g1,5573-g1,7156-g1,7809-g5,7153-g1,7941-g0,5271-g1,7735-g0"},
             {"refresh_type": "whole_refresh"}]}
b = {"log_type": "finder", "status": 1000, "date": "2022-06-07 15:34:57", "uid": "6249123767", "ip": "220.180.37.154",
     "Mozilla": "10C5395010", "module": [{"cate": "1006",
                                          "info": [{"containerid": "102803_ctg1_1780_-_ctg1_1780", "name": "发现"},
                                                   {"containerid": "232673", "name": "视频"},
                                                   {"containerid": "232660", "name": "娱乐"},
                                                   {"containerid": "231230_-_discover_-_index", "name": "体育"},
                                                   {"containerid": "232300_cardlist_discover_games", "name": "游戏"}]},
                                         {"cate": "1000",
                                          "info": [{"key": "柯洁"}, {"search_flag": "0", "key": "# 高考生上厕所身份证不慎被冲走#"},
                                                   {"key": "#热巴有一套秘籍#", "adid": 156531},
                                                   {"search_flag": "0", "key": "#特警在执勤考点偶遇自己高中老师#"},
                                                   {"search_flag": "0", "key": "#女生为了喜欢的东西有多勇#"},
                                                   {"search_flag": "0", "key": "红楼梦"},
                                                   {"search_flag": "5", "key": "#王祖蓝会帮李亚男跟父母沟通#"},
                                                   {"search_flag": "0", "key": "#全职妈妈把6年带娃 经历写进简历#"},
                                                   {"key": "#KPL夏季赛火热开打#"},
                                                   {"search_flag": "0", "key": "#乘风破浪姐姐们场外团建#"},
                                                   {"search_flag": "3", "key": "#高贵探花欧阳旭#"}, {"nav": "more"}]},
                                         {"cate": "1005", "info": [
                                             [{"pos": 0, "adid": "156841", "show_type": 2, "media_type": "image"}],
                                             [{"pos": 0, "adid": "156550", "show_type": 2, "media_type": "image"}],
                                             [{"pos": 0, "adid": "156832", "show_type": 2, "media_type": "image"}],
                                             [{"pos": 0, "adid": "156549", "show_type": 2, "media_type": "image"}],
                                             [{"pos": 0, "adid": "156534", "show_type": 2, "media_type": "image"}], [
                                                 {"pos": 0, "adid": "156751", "key": "领航计划", "is_topic": "1",
                                                  "show_type": 2, "media_type": "image"}]]}, {"cate": "1001", "info": [
            {"id": 329, "code": "kyqz"}, {"id": 1, "code": "zhaoren"}, {"id": 11, "code": "caijing"},
            {"id": 12, "code": "yinyue"}, {"id": 319, "code": "hotsquare"}, {"id": 3, "code": "youxi"},
            {"id": 313, "code": "bendi"}, {"id": 120, "code": "saishi"}, {"id": 16, "code": "meishi"},
            {"id": 310, "code": "chaoliu"}, {"id": 176, "code": "chaohua"}, {"id": 320, "code": "Ranking"},
            {"id": 4, "code": "zhibo"}, {"id": 15, "code": "qiche"}, {"id": 215, "code": "shiyong"},
            {"id": 325, "code": "discussroom"}, {"id": 324, "code": "HotTopic"}, {"id": 170, "code": "edu"},
            {"id": 14, "code": "fangchan"}, {"id": 10, "code": "hongrentao"}, {"id": 5, "code": "dianying"},
            {"id": 308, "code": "xinzhi"}, {"id": 169, "code": "weigongyi"}, {"id": 207, "code": "huodong"},
            {"id": 235, "code": "muying"}, {"id": 262, "code": "yushi"}]}], "v_p": "90",
     "cid": "102803_ctg1_1780_-_ctg1_1780", "sid": "t_wap_android", "type": "ctg1", "page": 1, "seqid": 719707129,
     "nettype": "wifi", "gis": ",", "ua": "Lenovo-Lenovo TB-J716F__weibo__12.5.3__android__android11", "refer": "",
     "uicode": "10001344", "luicode": "", "lfid": "",
     "ext": [{"misdtm": 1654587297964}, {"wm": "20003_0002"}, {"city_code": "800863401"}, {"web_degrade": "0"},
             {"ab": "5573-g1,7865-g0,7156-g1,5271-g0,6446-g1,7153-g0,7809-g0,7735-g0,6278-g0,6533-g1"},
             {"refresh_type": "whole_refresh"}]}
c = {"t": "3", "module": [{"cate": 5001,
                           "info": [{"num": 3007890, "key": "#男生被伯克利录取后陪同学参加高考#"}, {"num": 2839717, "key": "#高考作文#"},
                                    {"num": 2666777, "key": "#直击多地高考第一现场#"}, {"num": 2618753, "key": "全国甲卷 难"},
                                    {"num": 1642002, "key": "本手 妙手 俗手"}, {"num": 1442886, "key": "#美国丢弃了超8210万剂新冠疫苗#"},
                                    {"num": 1430661, "key": "#山东考生押中高考作文题#"},
                                    {"num": 1369650, "key": "#向往的生活导演否认有洗碗阿姨#"}, {"num": 1268478, "key": "柯洁"},
                                    {"num": 1105782, "key": "向往的生活 洗碗 阿姨"}, {"num": 1066954, "key": "#刘亦菲撞脸唐僧#"},
                                    {"num": 816975, "key": "#高考语文默写#"}, {"num": 787798, "key": "#高考生上厕所身份证不慎被冲走#"},
                                    {"num": 714779, "key": "#女子陪丈 夫复查发现自己早期胃癌#"}, {"num": 709256, "key": "#幸好毕业得早#"},
                                    {"num": 685134, "key": "红楼梦"}, {"num": 678200, "key": "#高贵探花欧阳旭#"},
                                    {"num": 560123, "key": "棋魂"}, {"num": 483564, "key": "#最后一年浙江卷#"},
                                    {"num": 482179, "key": "#易烊千玺玊尔演唱会视频#"}, {"num": 451991, "key": "#允儿在父母面前的求生欲有多强#"},
                                    {"num": 408458, "key": "#特警在执勤考点偶遇自己高中老师#"}, {"num": 400569, "key": "大学生凑热闹"},
                                    {"num": 399012, "key": "#乘风破浪姐姐们场外团建#"}, {"num": 395861, "key": "全国乙卷 题型"},
                                    {"num": 364338, "key": "#张雨绮问自己是什么咖位#"},
                                    {"num": 344219, "key": "#711门店卖36.2元过期食品被罚#"},
                                    {"num": 310967, "key": "#高考作文为什么如此受关注#", "issue_scenes": 1},
                                    {"num": 303758, "key": "#部分欧洲猴痘患者出现艾滋病共感染#"},
                                    {"num": 277170, "key": "#平安北京称今年北京考生很清醒#"},
                                    {"num": 275585, "key": "#全职妈妈把6年带娃经历写进简历#"}, {"num": 268521, "key": "#人生大事0624上映#"},
                                    {"num": 265443, "key": "#李易峰回应粉丝说喜欢看他被虐#"}, {"num": 248397, "key": "高考语文答案"},
                                    {"num": 244248, "key": "#深圳回应停车位纠纷处置进展#"}, {"num": 222428, "key": "#女生为了喜欢的东西有多勇#"},
                                    {"num": 211197, "key": "神之一手"}, {"num": 209985, "key": "#LPL夏季赛战队海报#"},
                                    {"num": 208154, "key": "#iOS16支持Switch手柄#"},
                                    {"num": 194949, "key": "#安妮海瑟薇Lisa同场活动合照#"}, {"num": 189868, "key": "梦中的那片海"},
                                    {"num": 178892, "key": "#杭州首创帮老人扫场所码功能#"},
                                    {"num": 176849, "key": "#张桂梅看着步入考场的孩子们笑了#"}, {"num": 168453, "key": "#KPL夏季赛火热开打#"},
                                    {"num": 167529, "key": "#拍出了诗经里的爱情#"}, {"num": 163928, "key": "#高考语文#"},
                                    {"num": 161172, "key": "#微作文 大赛#"}, {"num": 147694, "key": "#忘不了山东的丝瓜藤肉豆须#"},
                                    {"num": 146522, "key": "#深圳国资委通报国企书记事件#"}, {"num": 144377, "key": "天津作文 烟火气"}]},
                          {"cate": 5000, "info": [{"key": "#中国空间站等你来出差#"}]}, {"cate": 5002, "info": [
        {"key": "#陆航女飞行员登上高考作文题#", "num": 81219}, {"key": "#任子威祝高考生们金榜题名一举夺魁#", "num": 49425},
        {"key": "#熊猫睡姿难度太高#", "num": 121997}, {"key": "#一首歌致敬青春#", "num": 8280}, {"key": "#张雨绮都开始演妈了#", "num": 8411},
        {"key": "#哪个作文题最难 写#", "num": 65570}, {"key": "#王祖蓝会帮李亚男跟父母沟通#", "num": 8574},
        {"key": "#赞多式七上八下#", "num": 8491}, {"key": "#漳州市龙海区发现6例无症状感染者#", "num": 95268},
        {"key": "#周冬雨骑金榜题名电动车送考#", "num": 8356}, {"key": "#D2809殉职司机杨勇追 悼会举行#", "num": 61143},
        {"key": "#网飞极客周#", "num": 57528}, {"key": "#大白为次密接高考生陪考护航#", "num": 31698},
        {"key": "#吉林省12.5万名考生走进高考考场#", "num": 14377}, {"key": "#李诗沣退出印尼大师赛#", "num": 6784}]}, {"cate": 5023, "info": [
        {"key": "#向往的生活导演否认有洗碗阿姨#"}, {"key": "#刘亦菲撞脸唐僧#"}, {"key": "陈晓婚礼 柯南主题曲"}, {"key": "#2022下半年有什么电影值得期待#"},
        {"key": "#徐冬冬演的美女和丑女对比#"}, {"key": "#刘亦菲分享九宫格随拍#"}, {"key": "#僵尸校园续订第二季#"}, {"key": "# 考古陈晓和陈妍希从公开到结婚#"},
        {"key": "#朱雨辰细节好 到位#"}, {"key": "#侏罗纪世界3终极预告#"}]}, {"cate": 5081, "info": [{"roomid": 10161, "key": "#高考作文#"},
                                                                                   {"roomid": 10162, "key": "#高考语文#"},
                                                                                   {"roomid": 10150, "key": "#高考加油#"}]},
                          {"info": [{"key": "#山东考生押中高考作文题#"}, {"key": "#2022高考山东编排598810名考生#"},
                                    {"key": "#忘不了山东的丝瓜藤肉豆须#"}, {"key": "#山东的大学宿舍哪家强#"}, {"key": "#山东2022年高考人数约达80万#"},
                                    {"key": "#山东高考时间安排#"}, {"key": "#山东高考#"}, {"key": "#59.88万名山东学子今天上考场#"},
                                    {"key": "#2022山东高考语文作文#"}, {"key": "#高考期间山东多地实行错峰上下班#"}], "cate": 5005,
                           "set_citycode": "800863710"}], "status": 1000, "gis": ",",
     "cid": "106003type=25&t=3&disable_hot=1&filter_type=realtimehot", "type": 25, "page": "1", "errno": "",
     "ua": "Xiaomi-Redmi 10X Pro__weibo__12.4.2__android__android11", "log_type": "mobile_query", "uid": "6343744859",
     "seqid": "1654587296605023451326",
     "ext": [{"wm": "20005_0002"}, {"misdtm": 1654587296627}, {"position": "800863710"}, {"dgr": "0"},
             {"lcate": "1001"}, {"refresh_type": "0"}], "lfid": "102803_ctg1_1780_-_ctg1_1780",
     "refer": "seat=1&mi_cid=100103&filter_type=realtimehot&cate=10103&dgr=0&pos=0_0&lcate=1001&position={\"objectid\":\"8008637100000000000\",\"name\":\"\\u5a01\\u6d77\\u5e02\"}&c_type=30&display_time=1654587255&pre_seqid=1227610588",
     "ip": "112.54.81.39", "nettype": "", "size": 1, "date": "2022-06-07 15:34:56", "v_p": "90", "sid": "t_wap_android",
     "luicode": "10001344", "url": "http:\/\/was.search.weibo.com\/was\/was.php", "uicode": "10000011", "search": "",
     "Mozilla": "10C4295010"}
d = {"log_type": "finder", "status": 1000, "date": "2022-06-07 15:34:57", "uid": "2369336763", "ip": "182.119.200.211",
     "Mozilla": "10C5395060", "module": [{"cate": "1006",
                                          "info": [{"containerid": "102803_ctg1_1780_-_ctg1_1780", "name": "发现"},
                                                   {"containerid": "232660", "name": "娱乐"},
                                                   {"containerid": "232673", "name": "视频"},
                                                   {"containerid": "231230_-_discover_-_index", "name": "体育"},
                                                   {"containerid": "232300_cardlist_discover_games", "name": "游戏"}]},
                                         {"cate": "1000", "info": [{"key": "#山东考生押中高考作文题#"},
                                                                   {"search_flag": "5", "key": "#向往的生活导演否认有洗碗阿姨#"},
                                                                   {"search_flag": "5", "key": "#刘亦菲分享九宫格随拍#"},
                                                                   {"search_flag": "2", "key": "#郑州中学名师解读高考作文#"},
                                                                   {"search_flag": "0", "key": "全国甲卷 难"},
                                                                   {"adid": 156848, "key": "#2022北京高考#"},
                                                                   {"search_flag": "0", "key": "#男生被伯克利录取后陪同学参加高考#"},
                                                                   {"search_flag": "5", "key": "#华晨宇挡开路人手机#"},
                                                                   {"search_flag": "0", "key": "#允儿在父母面前的求生欲有多强#"},
                                                                   {"search_flag": "0", "key": "#高贵探花欧阳旭#"},
                                                                   {"search_flag": "3", "key": "#考古陈晓 和陈妍希从公开到结婚#"},
                                                                   {"nav": "more"}]}, {"cate": "1005", "info": [
            [{"pos": 0, "adid": "156550", "show_type": 2, "media_type": "image"}],
            [{"pos": 0, "adid": "156832", "show_type": 2, "media_type": "image"}],
            [{"pos": 0, "adid": "156534", "show_type": 2, "media_type": "image"}],
            [{"pos": 0, "adid": "156549", "show_type": 2, "media_type": "image"}],
            [{"pos": 0, "adid": "156751", "key": "领航计划", "is_topic": "1", "show_type": 2, "media_type": "image"}],
            [{"pos": 0, "adid": "156841", "show_type": 2, "media_type": "image"}]]}, {"cate": "1001", "info": [
            {"id": 329, "code": "kyqz"}, {"id": 5, "code": "dianying"}, {"id": 15, "code": "qiche"},
            {"id": 10, "code": "hongrentao"}, {"id": 325, "code": "discussroom"}, {"id": 3, "code": "youxi"},
            {"id": 313, "code": "bendi"}, {"id": 120, "code": "saishi"}, {"id": 16, "code": "meishi"},
            {"id": 310, "code": "chaoliu"}, {"id": 176, "code": "chaohua"}, {"id": 320, "code": "Ranking"},
            {"id": 1, "code": "zhaoren"}, {"id": 319, "code": "hotsquare"}, {"id": 4, "code": "zhibo"},
            {"id": 215, "code": "shiyong"}, {"id": 324, "code": "HotTopic"}, {"id": 170, "code": "edu"},
            {"id": 14, "code": "fangchan"}, {"id": 12, "code": "yinyue"}, {"id": 308, "code": "xinzhi"},
            {"id": 169, "code": "weigongyi"}, {"id": 11, "code": "caijing"}, {"id": 207, "code": "huodong"},
            {"id": 235, "code": "muying"}, {"id": 262, "code": "yushi"}]}], "v_p": "90",
     "cid": "102803_ctg1_1780_-_ctg1_1780", "sid": "t_wap_android", "type": "ctg1", "page": 1, "seqid": 47591655,
     "nettype": "wifi", "gis": "113.59588,34.75826", "ua": "HUAWEI-HMA-AL00__weibo__12.5.3__android__android10",
     "refer": "", "uicode": "10001344", "luicode": "", "lfid": "",
     "ext": [{"misdtm": 1654587297172}, {"wm": "9006_2001"}, {"city_code": "800864101"}, {"web_degrade": "0"},
             {"ab": "5238-g1,6533-g0,7865-g1,5573-g1,7156-g1,7153-g1,5271-g1,7735-g0,6278-g1"},
             {"refresh_type": "whole_refresh"}]}
e = {"search": "", "luicode": "10001344",
     "refer": "seat=1&lcate=1001&position=%7B%22objectid%22%3A%228008635050000000000%22%2C%22name%22%3A%22%5Cu6cc9%5Cu5dde%5Cu5e02%22%7D&c_type=30&lon=0&lat=0&mi_cid=100103&cate=10103&dgr=0&pos=0_0&filter_type=realtimehot&display_time=1654587294&pre_seqid=1662092953",
     "url": "http:\/\/was.search.weibo.com\/was\/was.php", "sid": "t_wap_ios",
     "cid": "106003type=25&t=3&disable_hot=1&filter_type=fun", "seqid": "165458729747002889302", "gis": "0,0", "t": "3",
     "errno": "", "size": 1, "module": [{"cate": 5009, "info": [{"key": "#向往的生活导演否认有洗碗阿姨#"}, {"key": "#刘亦菲撞脸唐僧#"},
                                                                {"key": "陈晓婚礼 柯南主题曲"}, {"key": "向往的生活 洗碗阿姨"},
                                                                {"key": "#张雨绮问自己是什么咖位#"}, {"key": "#刘亦菲分享九宫格随拍#"},
                                                                {"key": "#考古陈晓和陈妍希从公开到结婚#"}, {"key": "#高贵探花欧阳旭#"},
                                                                {"key": "#华晨宇挡开路人手 机#"}, {"key": "棋魂"},
                                                                {"key": "#允儿在父母面前的求生欲有多强#"},
                                                                {"key": "#安妮海瑟薇Lisa同场活动合照#"}, {"key": "#易烊千玺玊尔演唱会视频#"},
                                                                {"key": "#全职妈妈把6年带娃 经历写进简历#"},
                                                                {"key": "#2022下半年有什么电影值得期待#"}, {"key": "#拍出了诗经里的爱情#"},
                                                                {"key": "#一首歌致敬青春#"}, {"key": "#人生大事0624上映#"},
                                                                {"key": "#告五人巡演#"}, {"key": "#刘亦菲晒了一组户外美照#"},
                                                                {"key": "#乘风破浪姐姐们场外团建#"}, {"key": "#王祖蓝会帮李亚男跟父母沟通#"},
                                                                {"key": "#张雨绮都开始演妈了#"}, {"key": "#僵尸校园续订第二季#"},
                                                                {"key": "#现实版热血大片高考上映#"}, {"key": "#李易峰回应粉丝说喜欢看他被虐#"},
                                                                {"key": "#马嘉祺宋亚轩严浩翔贺峻霖今天高考#"},
                                                                {"key": "#李子锋每道菜都要放辣 椒#"}, {"key": "#周冬雨骑金榜题名电动车送考#"},
                                                                {"key": "梦中的那片海"}, {"key": "#黄轩祝高考生跳进更广阔的天地#"},
                                                                {"key": "#爸爸当家#", "roomid": 9762},
                                                                {"key": "#小黄人2正 式预告#"}, {"key": "#侏罗纪世界3终极预告#"},
                                                                {"key": "#李易峰毛遂自荐演暗夜行者#"}, {"key": "#朱雨辰台词好舒服#"},
                                                                {"key": "#叛逆者播出一周年#"}, {"key": "杨树扮男公关VS李大为扮男公关"},
                                                                {"key": "#朱雨辰细节好到位#"}, {"key": "#林深见鹿开播#"},
                                                                {"key": "#叛逆者为什么值得反复重温#"}, {"key": "#小贝饿了回应夜市遭遇男子骚扰#"},
                                                                {"key": "#张若昀祝 高考生们和李大为一样666#"},
                                                                {"key": "#欧阳娜娜和小时候的自己对话#"}, {"key": "#赞多式七上八下#"},
                                                                {"key": "#怎么办脱口秀专场连麦央视网#"}, {"key": "#夏日入侵企画#"},
                                                                {"key": "#网飞极客周#"}, {"key": "#电影内幕开机#"},
                                                                {"key": "#战至巅峰超燃宣传片#"}]}, {"cate": 5051, "info": [
        {"key": "#李易峰祝高考生鸿运当头#"}, {"key": "#说英雄全员邀你赴挽留宴#"}, {"key": "#容祖儿新歌告诉所有女孩要爱自己#"}, {"key": "#陈晓早期金发造型#"},
        {"key": "#汪小菲抠图直播#"}, {"key": "陈晓 中二少年"}, {"key": "#魏晨说不要给孩子说谎的机会#"}, {"key": "#网友高考语文古诗默写感谢陈飞宇#"},
        {"key": "#徐冬冬演的美女和丑女对比#"}, {"key": "#白百何三度回归李宗盛作品音乐剧#"}]}], "uicode": "10000011", "page": "1", "nettype": "",
     "ua": "iPhone14,5__weibo__12.5.2__iphone__os15.5", "lfid": "102803_ctg1_1780_-_ctg1_1780", "status": 1000,
     "uid": "5591430049",
     "ext": [{"wm": "3333_2001"}, {"misdtm": 1654587297305}, {"position": "800863505"}, {"dgr": "0"}, {"lcate": "1001"},
             {"refresh_type": "0"}], "type": 25, "ip": "220.162.16.128", "date": "2022-06-07 15:34:57",
     "Mozilla": "10C5293010", "log_type": "mobile_query", "v_p": "90"}
f = {"log_type": "finder", "status": 1000, "date": "2022-06-07 15:34:58", "uid": "5662855966", "ip": "117.176.185.78",
     "Mozilla": "10C5395060", "module": [{"cate": "1006",
                                          "info": [{"containerid": "102803_ctg1_1780_-_ctg1_1780", "name": "发现"},
                                                   {"containerid": "232673", "name": "视频"},
                                                   {"containerid": "232660", "name": "娱乐"},
                                                   {"containerid": "231230_-_discover_-_index", "name": "体育"},
                                                   {"containerid": "232300_cardlist_discover_games", "name": "游戏"}]},
                                         {"cate": "1000", "set_citycode": "800865101",
                                          "info": [{"key": "#男生被 伯克利录取后陪同学参加高考#"},
                                                   {"key": "#山东考生押中高考作文题#", "search_flag": "0"},
                                                   {"key": "#张雨绮都开始演妈了#", "search_flag": "5"},
                                                   {"key": "#高考生上厕所身份证不慎被冲走#", "search_flag": "0"},
                                                   {"key": "#李易峰回应粉丝说喜欢看他被虐#", "search_flag": "0"},
                                                   {"key": "#新手爸妈指南#", "adid": 156748},
                                                   {"key": "#乘风破浪姐姐们场外团建#", "search_flag": "0"},
                                                   {"key": "#叛逆者为什么值得反复重温#", "search_flag": "5"},
                                                   {"key": "#女生为了喜欢的东西有多勇#", "search_flag": "0"},
                                                   {"key": "梦中的那片海", "search_flag": "0"},
                                                   {"key": "#刘亦菲撞脸唐僧#", "search_flag": "3"}, {"nav": "more"}]},
                                         {"cate": "1005", "info": [[{"pos": 0, "adid": "156751", "key": "领航计划",
                                                                     "is_topic": "1", "show_type": 2,
                                                                     "media_type": "image"}], [
                                                                       {"pos": 0, "adid": "156549", "show_type": 2,
                                                                        "media_type": "image"}], [
                                                                       {"pos": 0, "adid": "156534", "show_type": 2,
                                                                        "media_type": "image"}], [
                                                                       {"pos": 0, "adid": "156832", "show_type": 2,
                                                                        "media_type": "image"}], [
                                                                       {"pos": 0, "adid": "156550", "show_type": 2,
                                                                        "media_type": "image"}], [
                                                                       {"pos": 0, "adid": "156841", "show_type": 2,
                                                                        "media_type": "image"}]]}, {"cate": "1001",
                                                                                                    "info": [{"id": 329,
                                                                                                              "code": "kyqz"},
                                                                                                             {"id": 5,
                                                                                                              "code": "dianying"},
                                                                                                             {"id": 319,
                                                                                                              "code": "hotsquare"},
                                                                                                             {"id": 324,
                                                                                                              "code": "HotTopic"},
                                                                                                             {"id": 1,
                                                                                                              "code": "zhaoren"},
                                                                                                             {"id": 3,
                                                                                                              "code": "youxi"},
                                                                                                             {"id": 313,
                                                                                                              "code": "bendi"},
                                                                                                             {"id": 120,
                                                                                                              "code": "saishi"},
                                                                                                             {"id": 16,
                                                                                                              "code": "meishi"},
                                                                                                             {"id": 310,
                                                                                                              "code": "chaoliu"},
                                                                                                             {"id": 176,
                                                                                                              "code": "chaohua"},
                                                                                                             {"id": 320,
                                                                                                              "code": "Ranking"},
                                                                                                             {"id": 4,
                                                                                                              "code": "zhibo"},
                                                                                                             {"id": 15,
                                                                                                              "code": "qiche"},
                                                                                                             {"id": 215,
                                                                                                              "code": "shiyong"},
                                                                                                             {"id": 325,
                                                                                                              "code": "discussroom"},
                                                                                                             {"id": 170,
                                                                                                              "code": "edu"},
                                                                                                             {"id": 14,
                                                                                                              "code": "fangchan"},
                                                                                                             {"id": 12,
                                                                                                              "code": "yinyue"},
                                                                                                             {"id": 10,
                                                                                                              "code": "hongrentao"},
                                                                                                             {"id": 308,
                                                                                                              "code": "xinzhi"},
                                                                                                             {"id": 169,
                                                                                                              "code": "weigongyi"},
                                                                                                             {"id": 11,
                                                                                                              "code": "caijing"},
                                                                                                             {"id": 207,
                                                                                                              "code": "huodong"},
                                                                                                             {"id": 235,
                                                                                                              "code": "muying"},
                                                                                                             {"id": 262,
                                                                                                              "code": "yushi"}]}],
     "v_p": "90", "cid": "102803_ctg1_1780_-_ctg1_1780", "sid": "t_wap_android", "type": "ctg1", "page": 1,
     "seqid": 1135533699, "nettype": "wifi", "gis": ",", "ua": "HUAWEI-ELE-AL00__weibo__12.5.3__android__android10",
     "refer": "discover|new_feed", "uicode": "10001344", "luicode": "", "lfid": "",
     "ext": [{"misdtm": 1654587298768}, {"wm": "9006_2001"}, {"city_code": "800865101"}, {"web_degrade": "0"},
             {"ab": "5897-g1,5573-g1,7156-g1,5271-g0,7153-g0,7735-g0,6533-g2,5709-g1,7865-g2"},
             {"refresh_type": "whole_refresh"}]}
g = {"log_type": "finder", "status": 1000, "date": "2022-06-07 15:34:58", "uid": "7212391678", "ip": "223.104.191.81",
     "Mozilla": "10C5293010", "module": [{"cate": "1006",
                                          "info": [{"containerid": "102803_ctg1_1780_-_ctg1_1780", "name": "发现"},
                                                   {"containerid": "232673", "name": "视频"},
                                                   {"containerid": "232660", "name": "娱乐"},
                                                   {"containerid": "231230_-_discover_-_index", "name": "体育"},
                                                   {"containerid": "232300_cardlist_discover_games", "name": "游戏"}]},
                                         {"cate": "1000", "info": [{"key": "#男生被伯克利录取后陪同学参 加高考#"},
                                                                   {"key": "#向往的生活导演否认有洗碗阿姨#", "search_flag": "5"},
                                                                   {"key": "#高考生上厕所身份证不慎被冲走#", "search_flag": "0"},
                                                                   {"key": "柯洁", "search_flag": "0"},
                                                                   {"key": "# 允儿在父母面前的求生欲有多强#", "search_flag": "0"},
                                                                   {"key": "#2022北京高 考#", "adid": 156848},
                                                                   {"key": "#刘亦菲分享九宫格随拍#", "search_flag": "5"},
                                                                   {"key": "陈晓婚礼 柯南主题曲", "search_flag": "5"},
                                                                   {"key": "#美国丢弃了超8210万剂新冠疫苗#", "search_flag": "0"},
                                                                   {"key": "#女子陪丈夫复查发现自己早期胃癌#", "search_flag": "0"},
                                                                   {"key": "#华晨宇挡 开路人手机#", "search_flag": "3"},
                                                                   {"nav": "more"}]}, {"cate": "1005", "info": [
            [{"pos": 0, "adid": "156832", "show_type": 2, "media_type": "image"}],
            [{"pos": 0, "adid": "156534", "show_type": 2, "media_type": "image"}],
            [{"pos": 0, "adid": "156549", "show_type": 2, "media_type": "image"}],
            [{"pos": 0, "adid": "156550", "show_type": 2, "media_type": "image"}],
            [{"pos": 0, "adid": "156751", "key": "领航计划", "is_topic": "1", "show_type": 2, "media_type": "image"}],
            [{"pos": 0, "adid": "156841", "show_type": 2, "media_type": "image"}]]}, {"cate": "1001", "info": [
            {"id": 329, "code": "kyqz"}, {"id": 120, "code": "saishi"}, {"id": 15, "code": "qiche"},
            {"id": 319, "code": "hotsquare"}, {"id": 12, "code": "yinyue"}, {"id": 3, "code": "youxi"},
            {"id": 313, "code": "bendi"}, {"id": 16, "code": "meishi"}, {"id": 310, "code": "chaoliu"},
            {"id": 176, "code": "chaohua"}, {"id": 320, "code": "Ranking"}, {"id": 1, "code": "zhaoren"},
            {"id": 4, "code": "zhibo"}, {"id": 215, "code": "shiyong"}, {"id": 325, "code": "discussroom"},
            {"id": 324, "code": "HotTopic"}, {"id": 170, "code": "edu"}, {"id": 14, "code": "fangchan"},
            {"id": 10, "code": "hongrentao"}, {"id": 5, "code": "dianying"}, {"id": 308, "code": "xinzhi"},
            {"id": 169, "code": "weigongyi"}, {"id": 11, "code": "caijing"}, {"id": 207, "code": "huodong"},
            {"id": 235, "code": "muying"}, {"id": 262, "code": "yushi"}]}], "v_p": "90",
     "cid": "102803_ctg1_1780_-_ctg1_1780", "sid": "t_wap_ios", "type": "ctg1", "page": 1, "seqid": 1841074249,
     "nettype": "4g", "gis": "0,0", "ua": "iPhone11,6__weibo__12.5.2__iphone__os15.2", "refer": "discover",
     "uicode": "10001344", "luicode": "", "lfid": "",
     "ext": [{"misdtm": 1654587298498}, {"wm": "3333_2001"}, {"city_code": "800863701"}, {"web_degrade": "0"},
             {"ab": "5238-g1,7865-g1,5573-g1,7156-g1,7809-g6,7153-g0,7941-g0,5271-g1,7735-g0"},
             {"refresh_type": "whole_refresh"}]}
h = {"log_type": "finder", "status": 1000, "date": "2022-06-07 15:34:58", "uid": "6031181237", "ip": "223.104.165.115",
     "Mozilla": "10C5293010", "module": [{"cate": "1006",
                                          "info": [{"containerid": "102803_ctg1_1780_-_ctg1_1780", "name": "发现"},
                                                   {"containerid": "232673", "name": "视频"},
                                                   {"containerid": "232660", "name": "娱乐"},
                                                   {"containerid": "231230_-_discover_-_index", "name": "体育"},
                                                   {"containerid": "232300_cardlist_discover_games", "name": "游戏"}]},
                                         {"cate": "1000",
                                          "info": [{"key": "#男生被伯克利录取后陪同学参加高考#"}, {"search_flag": "0", "key": "全国甲卷 难"},
                                                   {"key": "#荣耀70火爆开售#", "adid": 156558},
                                                   {"search_flag": "2", "key": "#浙江各地杨梅神仙打架#"},
                                                   {"search_flag": "5", "key": "# 向往的生活导演否认有洗碗阿姨#"},
                                                   {"key": "#王老吉高考打call我慕了#", "adid": 156772},
                                                   {"search_flag": "0", "key": "#山东考生押中高考作文题#"},
                                                   {"search_flag": "0", "key": "#美国丢弃了超8210万剂新冠疫苗#"},
                                                   {"search_flag": "0", "key": "#711门店卖36.2元过期食品被罚#"},
                                                   {"search_flag": "5", "key": "#考古陈晓和陈妍希从公开到结婚#"},
                                                   {"search_flag": "3", "key": "#华晨宇挡开路人手机#"}, {"nav": "more"}]},
                                         {"cate": "1005", "info": [
                                             [{"pos": 0, "adid": "156841", "show_type": 2, "media_type": "image"}],
                                             [{"pos": 0, "adid": "156832", "show_type": 2, "media_type": "image"}],
                                             [{"pos": 0, "adid": "156550", "show_type": 2, "media_type": "image"}],
                                             [{"pos": 0, "adid": "156534", "show_type": 2, "media_type": "image"}],
                                             [{"pos": 0, "adid": "156549", "show_type": 2, "media_type": "image"}], [
                                                 {"pos": 0, "adid": "156751", "key": "领航计划", "is_topic": "1",
                                                  "show_type": 2, "media_type": "image"}]]}, {"cate": "1001", "info": [
            {"id": 329, "code": "kyqz"}, {"id": 324, "code": "HotTopic"}, {"id": 325, "code": "discussroom"},
            {"id": 1, "code": "zhaoren"}, {"id": 11, "code": "caijing"}, {"id": 3, "code": "youxi"},
            {"id": 313, "code": "bendi"}, {"id": 120, "code": "saishi"}, {"id": 16, "code": "meishi"},
            {"id": 310, "code": "chaoliu"}, {"id": 176, "code": "chaohua"}, {"id": 320, "code": "Ranking"},
            {"id": 4, "code": "zhibo"}, {"id": 15, "code": "qiche"}, {"id": 215, "code": "shiyong"},
            {"id": 170, "code": "edu"}, {"id": 14, "code": "fangchan"}, {"id": 12, "code": "yinyue"},
            {"id": 10, "code": "hongrentao"}, {"id": 5, "code": "dianying"}, {"id": 308, "code": "xinzhi"},
            {"id": 169, "code": "weigongyi"}, {"id": 207, "code": "huodong"}, {"id": 235, "code": "muying"},
            {"id": 262, "code": "yushi"}]}], "v_p": "90", "cid": "102803_ctg1_1780_-_ctg1_1780", "sid": "t_wap_ios",
     "type": "ctg1", "page": 1, "seqid": 286633096, "nettype": "", "gis": "0,0",
     "ua": "iPhone13,2__weibo__12.5.2__iphone__os15.4", "refer": "discover", "uicode": "10001344", "luicode": "",
     "lfid": "",
     "ext": [{"misdtm": 1654587298220}, {"wm": "3333_2001"}, {"city_code": "800863308"}, {"web_degrade": "0"},
             {"ab": "5238-g1,5573-g0,7865-g1,5897-g0,7156-g1,7153-g1,7809-g0,5271-g1,7735-g0,5709-g1"},
             {"refresh_type": "whole_refresh"}]}
i = {"size": 1, "search": "", "page": "1", "nettype": "", "log_type": "mobile_query", "uid": "6172408731", "gis": ",",
     "url": "http:\/\/was.search.weibo.com\/was\/was.php",
     "ext": [{"wm": "9006_2001"}, {"misdtm": 1654587298275}, {"position": "800864201"}, {"dgr": "0"}, {"lcate": "1001"},
             {"refresh_type": "1"}],
     "refer": "seat=1&dgr=0&position={\"objectid\":\"8008642010000000000\",\"name\":\"\\u6b66\\u6c49\\u5e02\"}&filter_type=realtimehot&mi_cid=100103&cate=10103&lcate=1001&pos=0_0&c_type=30&display_time=1654587296&pre_seqid=843397677",
     "ip": "117.153.103.14", "module": [{"cate": 5001, "info": [{"num": 3007890, "key": "#男生被伯克利录取后陪同学参加高考#"},
                                                                {"num": 2839717, "key": "#高考作文#"},
                                                                {"num": 2666777, "key": "#直击多地高考第一现场#"},
                                                                {"num": 2658133, "adid": 156746, "key": "#世界品质 滋享健康#"},
                                                                {"num": 2618753, "key": "全国甲卷 难"},
                                                                {"num": 1642002, "key": "本手 妙手 俗手"},
                                                                {"num": 1442886, "key": "#美国丢弃了超8210万剂新冠疫苗#"},
                                                                {"num": 1430661, "key": "#山东考生押中高考作文题#"},
                                                                {"num": 1369650, "key": "#向往的生活导演否认有洗碗阿姨#"},
                                                                {"num": 1268478, "key": "柯洁"},
                                                                {"num": 1105782, "key": "向往的生活 洗碗阿姨"},
                                                                {"num": 1066954, "key": "#刘亦菲撞脸唐僧#"},
                                                                {"num": 816975, "key": "#高考语文默 写#"},
                                                                {"num": 787798, "key": "#高考生上厕所身份证不慎被冲走#"},
                                                                {"num": 714779, "key": "#女子陪丈夫复查发现自己早期胃癌#"},
                                                                {"num": 709256, "key": "#幸好毕业得早#"},
                                                                {"num": 685134, "key": "红楼梦"},
                                                                {"num": 678200, "key": "#高贵探花欧阳旭#"},
                                                                {"num": 560123, "key": "棋魂"},
                                                                {"num": 483564, "key": "#最后一年浙江卷#"},
                                                                {"num": 482179, "key": "#易烊千玺玊尔演唱会视频#"},
                                                                {"num": 451991, "key": "#允儿在父母面前的求生欲有多强#"},
                                                                {"num": 408458, "key": "#特警在执勤考点偶遇自己高中老师#"},
                                                                {"num": 400569, "key": "大学生凑热闹"},
                                                                {"num": 399012, "key": "#乘风破浪姐姐们场外团建#"},
                                                                {"num": 395861, "key": "全国乙卷 题型"},
                                                                {"num": 364338, "key": "#张雨绮问自己是什么咖位#"},
                                                                {"num": 344219, "key": "#711门店卖36.2元过期食品被罚#"},
                                                                {"num": 310967, "key": "#高考作文为什么如此受关注#",
                                                                 "issue_scenes": 1},
                                                                {"num": 303758, "key": "#部分欧洲猴痘患者出现艾滋病共感染#"},
                                                                {"num": 277170, "key": "#平安北京称今年北京考生很清醒#"},
                                                                {"num": 275585, "key": "#全职妈妈把6年带娃经历写进简历#"},
                                                                {"num": 268521, "key": "#人生大事0624上映#"},
                                                                {"num": 265443, "key": "#李易峰回应粉丝说喜欢看他被虐#"},
                                                                {"num": 248397, "key": "高考 语文答案"},
                                                                {"num": 244248, "key": "#深圳回应停车位纠纷处置进展#"},
                                                                {"num": 222428, "key": "#女生为了喜欢的东西有多勇#"},
                                                                {"num": 211197, "key": "神之一手"},
                                                                {"num": 209985, "key": "#LPL夏季赛战队海报#"},
                                                                {"num": 208154, "key": "#iOS16支持Switch手柄#"},
                                                                {"num": 194949, "key": "#安妮海瑟薇Lisa同场活动合照#"},
                                                                {"num": 189868, "key": "梦中的那片海"},
                                                                {"num": 178892, "key": "#杭州首创帮老人扫场所码功能#"},
                                                                {"num": 176849, "key": "#张桂梅看着步入考场的孩子们笑了#"},
                                                                {"num": 168453, "key": "#KPL夏季赛火热开打#"},
                                                                {"num": 167529, "key": "#拍出了诗经里的爱情#"},
                                                                {"num": 163928, "key": "#高考语文#"},
                                                                {"num": 161172, "key": "#微作文大赛#"},
                                                                {"num": 147694, "key": "#忘不了山东的丝瓜藤肉豆须#"},
                                                                {"num": 146522, "key": "#深圳国资委通报国企书记事件#"},
                                                                {"num": 144377, "key": "天津作文 烟火 气"}]},
                                        {"cate": 5000, "info": [{"key": "#推动人 类科学事业发展#"}]}, {"cate": 5002, "info": [
            {"key": "#一首歌致敬青春#", "num": 8280}, {"key": "#张雨绮都开始演妈了#", "num": 8411},
            {"key": "#陆航女飞行员登上高考作文题#", "num": 81219}, {"key": "#任子威祝高考生们金榜题名一举夺魁#", "num": 49425},
            {"key": "#熊猫睡姿难度太高#", "num": 121997}, {"key": "#保安背受伤业主下16楼避险累到呕吐#", "num": 60165},
            {"key": "#王祖蓝会帮李亚男跟父母沟通#", "num": 8574}, {"key": "#漳州市龙海区发现6例无症状感染者#", "num": 95268},
            {"key": "#河北一考点家长牵马陪考#", "num": 19691}, {"key": "#D2809殉职司机杨勇追悼会举行#", "num": 61143},
            {"key": "#李易峰祝高考生鸿运当头#", "num": 66881}, {"key": "#吉林省12.5万名考生走进高考考场#", "num": 14377},
            {"key": "#约翰逊赢得保守党党内不信任投票#", "num": 9423}, {"key": "#河北52.74万人参加高考统考#", "num": 9359},
            {"key": "#2022山西高考第一天#", "num": 9133}]}, {"cate": 5023,
                                                      "info": [{"key": "#向 往的生活导演否认有洗碗阿姨#"}, {"key": "#刘亦菲撞脸唐僧#"},
                                                               {"key": "陈晓婚礼 柯南主题曲"}, {"key": "#周冬雨骑 金榜题名电动车送考#"},
                                                               {"key": "#告五人巡演#"}, {"key": "#陈晓 早期金发造型#"},
                                                               {"key": "#黄轩祝高考生跳进更广阔的天地#"},
                                                               {"key": "#张若昀祝高考生们和李大为一样666#"},
                                                               {"key": "#徐冬冬演的美女和丑女对比#"},
                                                               {"key": "#王祖蓝说不要把沟通留在生命的最后阶 段#"}]}, {"cate": 5081,
                                                                                                    "info": [{
                                                                                                                 "key": "#高考作文#",
                                                                                                                 "roomid": 10161},
                                                                                                             {
                                                                                                                 "key": "#高考语文#",
                                                                                                                 "roomid": 10162},
                                                                                                             {
                                                                                                                 "key": "#高考加油#",
                                                                                                                 "roomid": 10150}]},
                                        {"info": [{"key": "#武汉一考生高考前弄丢准考证#"}, {"key": "#2022年湖北高考作文#"},
                                                  {"key": "#武汉闹市中的老破房啥时能拆#"}, {"key": "#今年湖北消费券可能更容易抢#"},
                                                  {"key": "#湖 北高考作文本手妙手俗手#"}, {"key": "#武汉东湖和杭州西湖谁更美#"},
                                                  {"key": "#6月至10月湖北将发放三轮消费券#"}, {"key": "#武汉人吃菜最香的时候到了#"},
                                                  {"key": "#武汉一小区栀子花频遭团 灭式采摘#"}, {"key": "#武汉多个小区有蛇出现#"}],
                                         "cate": 5005}], "Mozilla": "10C5395060", "seqid": "165458729827602890315",
     "v_p": "90", "lfid": "102803_ctg1_1780_-_ctg1_1780", "luicode": "10001344", "status": 1000, "errno": "",
     "uicode": "10000011", "type": 25, "ua": "HUAWEI-WLZ-AN00__weibo__12.5.3__android__android10",
     "date": "2022-06-07 15:34:58", "t": "3", "cid": "106003type=25&t=3&disable_hot=1&filter_type=realtimehot",
     "sid": "t_wap_android"}
g = {"Mozilla": "10C5393010", "errno": "", "luicode": "10001344", "url": "http:\/\/was.search.weibo.com\/was\/was.php",
     "uicode": "10000011", "module": [{"info": [{"key": "#向往的 生活导演否认有洗碗阿姨#"}, {"key": "#刘亦菲撞脸唐僧#"},
                                                {"key": "陈晓婚礼 柯南主题曲"}, {"key": "向往的生活 洗碗阿姨"}, {"key": "#张雨绮问自己是什么咖位#"},
                                                {"key": "#刘亦菲分享九宫格随拍#"}, {"key": "#考古陈晓和陈妍希从公开到结婚#"},
                                                {"key": "#高贵探花欧阳旭#"}, {"key": "#华晨宇挡开路人手机#"}, {"key": "棋魂"},
                                                {"key": "#允儿在父母面前 的求生欲有多强#"}, {"key": "#安妮海瑟薇Lisa同场活动合照#"},
                                                {"key": "#易烊千玺玊尔演唱会视频#"}, {"key": "#全职妈妈把6年带娃经历写进简历#"},
                                                {"key": "#2022下半年有什么电影值得期待#"}, {"key": "#拍出了诗经里的爱情#"},
                                                {"key": "#一首歌致敬青春#"}, {"key": "#人生大事0624上映#"}, {"key": "#告五人巡演#"},
                                                {"key": "#刘亦菲晒了一组户外美照#"}, {"key": "#乘风 破浪姐姐们场外团建#"},
                                                {"key": "#王祖蓝会帮李亚男跟父母沟通#"}, {"key": "#张雨绮都开始演妈了#"},
                                                {"key": "#僵尸校园续订第二季#"}, {"key": "#现实版热血大片高考上映#"},
                                                {"key": "#李易峰回应粉丝说喜欢看他被虐#"}, {"key": "#马嘉祺宋亚轩严浩翔贺峻霖今天高考#"},
                                                {"key": "#李子锋每道菜都要放辣椒#"}, {"key": "#周冬雨骑金榜题名电动车送考#"}, {"key": "梦中的那片海"},
                                                {"key": "#黄轩祝高考生跳进更广阔的天地#"}, {"roomid": 9762, "key": "#爸爸当家#"},
                                                {"key": "#小黄人2正式预告#"}, {"key": "#侏罗纪世界3终极预告#"},
                                                {"key": "#李 易峰毛遂自荐演暗夜行者#"}, {"key": "#朱雨辰台词好舒服#"},
                                                {"key": "#叛逆者播出一周年#"}, {"key": "杨树扮男公关VS李大为扮男公关"},
                                                {"key": "#朱雨辰细 节好到位#"}, {"key": "#林深见鹿开播#"}, {"key": "#叛逆者为什么值得反复重温#"},
                                                {"key": "#小贝饿了回应夜市遭遇男子骚扰#"}, {"key": "#张若昀祝高考生们和李大为一样666#"},
                                                {"key": "#欧阳娜娜和小时候的自己对话#"}, {"key": "#赞多式七上八下#"},
                                                {"key": "#怎么办 脱口秀专场连麦央视网#"}, {"key": "#夏日入侵企画#"}, {"key": "#网飞极客周#"},
                                                {"key": "#电影内幕开机#"}, {"key": "#战 至巅峰超燃宣传片#"}], "cate": 5009}, {
                                          "info": [{"key": "#李易峰祝高考生鸿运当头#"}, {"key": "#说英雄全员邀你赴挽留宴#"},
                                                   {"key": "#容祖儿新歌告诉所有女孩要爱自己#"}, {"key": "#魏晨说不要给孩子说谎的机会#"},
                                                   {"key": "#白百何三度回归李宗盛作品音乐剧#"}, {"key": "#徐冬冬演的美女和丑女对比#"},
                                                   {"key": "#张效诚的情绪管理能力#"}, {"key": "陈晓 中二 少年"},
                                                   {"key": "#吉克隽逸分享高考必备物品清单#"}, {"key": "#宋朝人的生活仪式感#"}], "cate": 5051}],
     "size": 1, "t": "3", "sid": "t_wap_ios", "status": 1000, "type": 25, "lfid": "102803_ctg1_1780_-_ctg1_1780",
     "date": "2022-06-07 15:34:57", "cid": "106003type=25&t=3&disable_hot=1&filter_type=fun",
     "seqid": "165458729739809944101", "page": "1", "nettype": "", "ua": "iPhone13,2__weibo__12.5.3__iphone__os15.5",
     "log_type": "mobile_query", "uid": "3250299882", "gis": "120.0305767160233,30.27688422638611",
     "ext": [{"wm": "3333_2001"}, {"misdtm": 1654587297419}, {"position": "800863301"}, {"dgr": "0"}, {"lcate": "1000"},
             {"refresh_type": "0"}], "search": "",
     "refer": "lcate=1000&pos=10&query=华晨宇挡开路人手机&from_finder=1&recommend_hotsearch=1", "ip": "42.120.74.30",
     "v_p": "90"}
